name: Deploy Vue App
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: get the repository code
        uses: actions/checkout@v3.5.2
      - name: install dependecies
        run: npm ci
  link:
    runs-on: windows-latest
    steps:
      - name: get the repository code
        uses: actions/checkout@v3.5.2
      - name: install dependecies
        run: npm ci
      - name: lint application
        run: npm run lint
  build:
    runs-on: windows-latest
    steps:
      - name: get the repository code
        uses: actions/checkout@v3.5.2
      - name: install dependecies
        run: npm ci
      - name: buld
        run: npm run build
      - name: Deploy
        run: echo Deploying...

        